name: DistContactTracing
options:
  bundleIdPrefix: com.dist-contact-tracing.app
targets:
  DistContactTracing:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [src]
    settings:
      configs:
        debug:
        release: