name: DistContactTracing
options:
  bundleIdPrefix: com.dist-contact-tracing.app
settings:
  DEVELOPMENT_TEAM: VDQM747B3N
targets:
  MySharedAir:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [src]
    settings:
      configs:
        debug:
        release: